# Basic Information 
title: Xingli Fang
position: Ph.D. Student in Computer Science
affiliation: NC State University
affiliation_link: https://www.ncsu.edu/
department: Department of Computer Science
department_link: https://www.csc.ncsu.edu/
email: xfang23@ncsu.edu
address: Raleigh, NC, USA

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Xingli Fang
description: Xingli Fang Academic Page
canonical: https://xfangsn.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=GJtATkAAAAAJ
#linked_in: https://www.linkedin.com/in/xingli-fang-7817b7231/
#resume: https://google.com

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.ico
favicon_dark: ./assets/img/favicon.ico

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - jekyll-jemdoc.gemspec
