# Site settings
title: Mohammad Afzal Shadab
email: mashadab@utexas.edu
description: Academic webpage of Mohammad Afzal Shadab
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
google_analytics:

# Footer info
affiliation: >
    Mohammad Afzal Shadab<br/>
    Graduate Research Assistant and PhD Student <br/>
    <a href="https://www.oden.utexas.edu/" target="_blank">Oden Institute for Computational Engineering and Sciences </a><br/> \n The University of Texas at Austin

location: >
  <a href="http://www.mce.caltech.edu/about/gates_thomas" target="_blank">Gates-Thomas Laboratory</a><br/>
  California Institute of Technology <br/>
  1200 E California Blvd<br/>
  Pasadena, CA 91125, MC104-44

contact: >
    <a href="mailto:mashadab@utexas.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Afzal via email</a> <br/>
    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Acknowledgements!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
#  - name: talks
  - name: research
  - name: laboratory
#  - name: team
# - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: true

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - switch_theme.sh
  - makebib.py
