# Site settings
title: Xingli Fang
email: xfang13@syr.edu
description: Academic webpage of Xingli Fang
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
google_analytics:

# Footer info
affiliation: >
    Xingli Fang<br/>
    Ph.D. Student <br/>
    <a href="https://www.csc.ncsu.edu/" target="_blank">Computer Science </a><br/> North Carolina State University

location: >
#  <a href="https://www.jsg.utexas.edu/hesse/marc-hesse/" target="_blank">Geological Fluid Mechanics Group, UT Austin</a><br/>
#  POB 3SEo5M <br/>
#  Austin, TX 78712-1199

contact: >
    <a href="mailto:xfang13@syr.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact X.Fang via email</a> <br/>
#    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Acknowledgements!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: publications
#  - name: talks
#  - name: projects
#  - name: laboratory
#  - name: team
  - name: teaching

# Do you want to group your publications by year? {true/false}
group_pub_by_year: false

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - switch_theme.sh
  - makebib.py
