conference:
  - content: "<strong>[June 2024]</strong> 2nd Workshop on Advancing Neural Network Training: Computational Efficiency, Scalability, and Resource Optimization (WANT@ICML 2024), serve as reviewer"
    link: https://want-ai-hpc.github.io/icml2024/about/

